In [1]:
import sys
import numpy as np

In [2]:
print('Python version: {}'.format(sys.version))
print('NumPy version: {}'.format(np.__version__))

Python version: 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
NumPy version: 1.13.3


**Create ndarray**

In [71]:
# notes: 
# 1. NumPy array or so called ndarray must contain homogeneous object, which means all elements must be of the same type 
# 2. difference between np.array() and np.asarray(): np.array() always return a copy, np.asarray() returns a view if the argument is ndarray already
# 3. arithmetic operations are performed element-wise given two equal-size ndarrays

# scenario 1: convert existing sequence type (list, tuple, or set) to ndarray
py_list = list(range(10))
py_tuple = tuple(range(10))
py_set = set(range(10))
np_array = np.array(py_list)
print('constructed using python list: {}'.format(np_array))
np_array = np.array(py_tuple)
print('constructed using python tuple: {}'.format(np_array))
# need to convert set to list before converting to ndarray
np_array = np.array(list(py_set))
print('constructed using python set: {}'.format(np_array))
np_array = np.arange(0, 10, 2)
print('constructed using .arange() method: {}'.format(np_array))

# scenario 2: create ndarray filled with zeros
np_array = np.zeros(10)
print(np_array)
np_array = np.zeros((2,2))        # pass in the shape as a tuple
print(np_array)
# return an array of zeros with the same shape and type as a given array
original_array = np.random.rand(3,3)
np_array = np.zeros_like(original_array)
print('The shapes of the two arrays are the same: {}'.format(original_array.shape == np_array.shape))
print('The data types of the two arrays are the same: {}'.format(original_array.dtype == np_array.dtype))

# scenario 3: create ndarry filled with ones
np_array = np.ones(10)
print(np_array)
np_array = np.ones((2,2)) 
print(np_array)
# return an array of ones with the same shape and type as a given array
original_array = np.random.rand(3,3)
np_array = np.ones_like(original_array)
print('The shapes of the two arrays are the same: {}'.format(original_array.shape == np_array.shape))
print('The data types of the two arrays are the same: {}'.format(original_array.dtype == np_array.dtype))

# scenario 4: create ndarray filled with arbitrary data
np_array = np.empty((3, 3))                  # notice .empty() initializes ndarray with arbitrary data rather than 0
print(np_array)
# return an array of arbitrary data with the same shape and type as a given array
original_array = np.random.rand(3,3)
np_array = np.empty_like(original_array)
print('The shapes of the two arrays are the same: {}'.format(original_array.shape == np_array.shape))
print('The data types of the two arrays are the same: {}'.format(original_array.dtype == np_array.dtype))

# scenario 5: create ndarray filled with nan
# sub method i) use ndarray.fill() method
np_array = np.empty((3,3,3))
np_array.fill(np.nan)
print(np_array)
# sub method ii) use np.full() or np.full_like() method
np_array = np.full((2, 2), np.nan)
print(np_array)
# return an array of filled values with the same shape and type as a given array
original_array = np.empty((3,3,3))
np_array = np.full_like(original_array, np.nan)
print(np_array)

# scenario 6: create n by n identity matrix
n = 10
# np.eye() method
np_array = np.eye(n)
print(np_array)
# np.identity() method
np_array = np.identity(n)
print(np_array)

constructed using python list: [0 1 2 3 4 5 6 7 8 9]
constructed using python tuple: [0 1 2 3 4 5 6 7 8 9]
constructed using python set: [0 1 2 3 4 5 6 7 8 9]
constructed using .arange() method: [0 2 4 6 8]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.]
 [ 0.  0.]]
The shapes of the two arrays are the same: True
The data types of the two arrays are the same: True
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[ 1.  1.]
 [ 1.  1.]]
The shapes of the two arrays are the same: True
The data types of the two arrays are the same: True
[[  6.95224883e-310   4.64240755e-310   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  8.70018275e-313   0.00000000e+000   3.95252517e-322]]
The shapes of the two arrays are the same: True
The data types of the two arrays are the same: True
[[[ nan  nan  nan]
  [ nan  nan  nan]
  [ nan  nan  nan]]

 [[ nan  nan  nan]
  [ nan  nan  nan]
  [ nan  nan  nan]]

 [[ nan  nan  nan]
  [ nan  nan  nan]
  [ nan  nan  nan]]]
[[ nan  nan]
 

**Check ndarray properties**

In [88]:
np_array = np.random.rand(2, 2, 2)

In [89]:
# dimension
np_array.ndim

3

In [90]:
# shape - return a tuple
np_array.shape

(2, 2, 2)

In [95]:
# memory size of each item
np_array.itemsize

8

In [91]:
# size - total number of elements
np_array.size

8

In [96]:
# memory size - number of bytes = np.size * np.itemsize
np_array.nbytes

64

In [97]:
# data type
np_array.dtype

dtype('float64')

In [98]:
# data type (get the string only)
np_array.dtype.name

'float64'