In [3]:
## check python version
import sys
print(sys.version)

3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]


**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [7]:
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/eric/anaconda2/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eric/anaconda2/envs/py36/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/eric/anaconda2/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eric/anaconda2/envs/py36/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/eric/anaconda2/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eric/anaconda2/envs/py36/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/eric/anaconda2/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eric/anaconda2/envs/py36/include']


**3. Create a null vector of size 10**

In [15]:
## null vector is a vector filled with all zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**4. How to get the documentation of the numpy add function from the command line?**

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

**5. Create a null vector of size 10 but the fifth value which is 1**

In [17]:
v = np.zeros(10)
v[4] = 1
print(v)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


**6. Create a vector with values ranging from 10 to 49**

In [25]:
## convert an array to np array
v = np.array(range(10, 50))
print(v)
## a more concise way
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**7. Reverse a vector (first element becomes last)**

In [28]:
v = np.arange(20)
print(v)
rev_v = v[::-1]
print(rev_v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**8. Create a 3x3 matrix with values ranging from 0 to 8**

In [38]:
## use object method
print(np.arange(9).reshape((3,3)))
## or use numpy built-in method
print(np.reshape(np.arange(9), (3,3)))
## default reshape order is C-like (row major)
## but we can set it to Fortran-like (column major)
print(np.reshape(np.arange(9), (3,3), order='F'))
## use -1 for dimension inference
print(np.arange(9).reshape((3,-1)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**9. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [44]:
arr = [1,2,0,0,4,0]
## nonzero() method returns the indices of non-zero elements
ix = np.nonzero(arr)
print(ix)

(array([0, 1, 4]),)


**10. Create a 3x3 identity matrix**

In [49]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

**11. Create a 3x3x3 array with random values**

In [54]:
## method 1
np.random.random(9).reshape((3,3))
## method 2
np.random.rand(3,3)

array([[ 0.74223736,  0.59361654,  0.51613457],
       [ 0.49693385,  0.44842218,  0.48923154],
       [ 0.24940877,  0.39752378,  0.3460737 ]])

**12. Create a 10x10 array with random values and find the minimum and maximum values**

In [59]:
mat = np.random.rand(10,10)
print(mat.min(), mat.max())

0.0220172166814 0.987606320689


**13. Create a random vector of size 30 and find the mean value**

In [60]:
arr = np.random.random(30)
print(arr.mean())

0.394862674531


**14. Create a 2d array with 1 on the border and 0 inside**

In [62]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


**15. What is the result of the following expression?**

In [63]:
0 * np.nan           ## np.nan
np.nan == np.nan     ## False
np.inf > np.nan      ## False
np.nan - np.nan      ## np.nan
0.3 == 3 * 0.1       ## false

False

**16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [72]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**17. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [74]:
arr = np.zeros((8,8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

**19. Create a checkerboard 8x8 matrix using the tile function**

In [77]:
arr = np.tile([[1,0], [0,1]], (4,4))
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**20. Normalize a 5x5 random matrix**

In [89]:
mat = np.random.rand(5,5)
mat / mat.sum(axis=0)

array([[  3.14360404e-01,   2.17237611e-02,   1.87611954e-01,
          2.00243024e-01,   8.04131111e-02],
       [  1.11485983e-04,   3.07354965e-01,   2.07545860e-01,
          1.58126895e-01,   1.90365503e-01],
       [  2.20497529e-01,   2.85538711e-01,   3.05357957e-01,
          2.21874814e-01,   2.86943075e-01],
       [  2.54534698e-01,   1.27168806e-01,   3.80914058e-02,
          2.10892829e-01,   2.95894151e-01],
       [  2.10495883e-01,   2.58213757e-01,   2.61392823e-01,
          2.08862438e-01,   1.46384160e-01]])

**21. Create a custom dtype that describes a color as four unisgned bytes (RGBA)**

In [90]:
color = np.dtype([('r', np.ubyte, 1), 
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)])

**22. Multiply a 5x3 matrix by a 3x2 matrix (matrix product)**

In [94]:
mat_a = np.random.rand(5,3)
mat_b = np.random.rand(3,2)
## method 1
mat_a.dot(mat_b)
## method 2
np.dot(mat_a, mat_b)
## method 3
mat_a @ mat_b

array([[ 1.38177364,  1.00013201],
       [ 0.19912419,  0.20276368],
       [ 0.46768494,  0.33986656],
       [ 0.49613513,  0.29230157],
       [ 0.97925115,  0.65057373]])

**23. Given a 1D array, negate all elements which are between 3 and 8, in place**

In [107]:
arr = np.random.random(50) * 10
print(arr)
## arr[(3 < arr) & (arr < 8)] = -arr[(3 < arr) & (arr < 8)]
## syntactic sugar 
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 7.55880804  2.56937913  0.86155133  5.5713086   5.32631131  7.0752208
  3.08931086  6.93811512  5.62999505  4.39671938  8.77468063  2.89162159
  3.21848127  4.40478281  8.71538966  0.77232715  3.13566049  4.55609289
  0.43846508  6.60487367  7.57625868  6.592332    2.462563    1.56698155
  2.10027123  7.62153148  8.765343    0.37493254  0.96696378  9.21286468
  7.58409631  1.09599288  1.94678561  3.48856522  8.44596601  4.50151931
  2.01975267  3.5489009   8.74119661  7.26777528  8.34815196  6.28067456
  6.6296102   5.17148582  9.03142518  1.50773903  1.64173857  7.72026239
  6.95477741  0.62931176]
[-7.55880804  2.56937913  0.86155133 -5.5713086  -5.32631131 -7.0752208
 -3.08931086 -6.93811512 -5.62999505 -4.39671938  8.77468063  2.89162159
 -3.21848127 -4.40478281  8.71538966  0.77232715 -3.13566049 -4.55609289
  0.43846508 -6.60487367 -7.57625868 -6.592332    2.462563    1.56698155
  2.10027123 -7.62153148  8.765343    0.37493254  0.96696378  9.21286468
 -7.58409631  1.09599288  1

**24. What is the output of the following script?**

In [109]:
print(sum(range(5),-1))    ## 
from numpy import *
print(sum(range(5),-1))

10
10


**25. Consider an integer vector Z, which of these expressions are legal? **

In [133]:
Z**Z              ## legal: element-wise arithmetic operations
2 << Z >> 2       ## legal: from left to right
Z <- Z            ## legal: element-wise comparison, space is ignored <- is equivalent to <   -
1j*Z              ## legal: complex arithmetic operations
Z/1/1             ## legal: same to the second
Z<Z>Z             ## illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**26. What are the result of the following expressions?**

In [9]:
np.array(0) // np.array(0)

/home/eric/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [10]:
np.array(0) // np.array(0.)

/home/eric/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in floor_divide
  """Entry point for launching an IPython kernel.


nan

In [11]:
np.array(0) / np.array(0)

/home/eric/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [8]:
np.array(0) / np.array(0.)

/home/eric/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

**27. How to round away from zero a float array?**

In [15]:
arr = np.random.uniform(-10,+10,10)
print(np.trunc(arr + np.copysign(0.5, arr)))

[ -9.  -2.   4.  -5.   2.  -7. -10.   3.   7.  -2.]


**28. Extract the integer part of a random array using 5 different methods**

In [28]:
arr = np.random.random(10) * 10
## method 1 
np.floor(arr)
## method 2
np.ceil(arr) - 1
## method 3
arr.astype('int')
## method 4
np.trunc(arr)   ## return type is float
## method 5
arr - arr % 1   ## return type is float

array([ 9.,  9.,  4.,  8.,  6.,  9.,  7.,  9.,  9.,  1.])

**29. Create a 5x5 matrix with row values ranging from 0 to 4**

In [38]:
## method 1
print(np.array([range(5)] * 5).reshape((5,5)))
## method 2
arr = np.zeros((5,5))   ## return type is float
arr += np.arange(5)     ## broadcasting
print(arr.astype('int'))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**30. Consider a generator function that generates 10 integers and use it to build an array**

In [41]:
def gen_int():
    yield from range(10)

## python solution
list(gen_int())
## numpy solution
np.fromiter(gen_int(), dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**31. Create a vector of size 10 with values ranging from 0 to 1, both excluded**

In [46]:
arr = np.linspace(0, 1, 10, endpoint=True)
print(arr)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


**32. Create a random vector of size 10 and sort it**

In [49]:
arr = np.random.random(10)
print(arr)
## sort by universal function 
print(np.sort(arr))
## in-place sorting
arr.sort()
print(arr)

[ 0.92539518  0.22064327  0.68454159  0.05809342  0.23319705  0.19610659
  0.46456822  0.02673259  0.54342059  0.15630066]
[ 0.02673259  0.05809342  0.15630066  0.19610659  0.22064327  0.23319705
  0.46456822  0.54342059  0.68454159  0.92539518]
[ 0.02673259  0.05809342  0.15630066  0.19610659  0.22064327  0.23319705
  0.46456822  0.54342059  0.68454159  0.92539518]


**33. How to sum a small array faster than np.sum?**

In [3]:
arr = np.arange(1000)
%timeit arr.sum()

1.76 µs ± 65.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
%timeit np.add.reduce(arr)

1.47 µs ± 47.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**34. Consider two random array A anb B, check if they are equal**

In [11]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
np.allclose(A, B)

True

**35. Make an array immutable (read-only)**

In [16]:
arr = np.arange(10)
arr.flags.writeable = False

**36. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates**

In [20]:
arr = np.random.rand(10, 2)
X, Y = arr[:,0], arr[:,1]
r = np.sqrt(X ** 2 + Y ** 2)
rho = np.arctan2(Y,X)
print(r)
print(rho)

[ 0.94625096  0.65269976  0.79346313  0.39709301  0.89403828  0.58189521
  0.9042091   0.98485173  0.94050444  0.63463298]
[ 0.26089143  0.63397477  0.4274596   0.79778862  0.05371436  1.24695853
  0.19432064  0.22617316  1.17272008  1.38461743]


**37. Create random vector of size 10 and replace the maximum value by 0**

In [25]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[ 0.38039391  0.55831512  0.24467996  0.38207356  0.54537424  0.73148166
  0.04931551  0.47330017  0.3704435   0.95575403]
[ 0.38039391  0.55831512  0.24467996  0.38207356  0.54537424  0.73148166
  0.04931551  0.47330017  0.3704435   0.        ]


**38. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area**

In [27]:
arr = np.zeros((10,10), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(arr)

[[( 0.        ,  0.        ) ( 0.11111111,  0.        )
  ( 0.22222222,  0.        ) ( 0.33333333,  0.        )
  ( 0.44444444,  0.        ) ( 0.55555556,  0.        )
  ( 0.66666667,  0.        ) ( 0.77777778,  0.        )
  ( 0.88888889,  0.        ) ( 1.        ,  0.        )]
 [( 0.        ,  0.11111111) ( 0.11111111,  0.11111111)
  ( 0.22222222,  0.11111111) ( 0.33333333,  0.11111111)
  ( 0.44444444,  0.11111111) ( 0.55555556,  0.11111111)
  ( 0.66666667,  0.11111111) ( 0.77777778,  0.11111111)
  ( 0.88888889,  0.11111111) ( 1.        ,  0.11111111)]
 [( 0.        ,  0.22222222) ( 0.11111111,  0.22222222)
  ( 0.22222222,  0.22222222) ( 0.33333333,  0.22222222)
  ( 0.44444444,  0.22222222) ( 0.55555556,  0.22222222)
  ( 0.66666667,  0.22222222) ( 0.77777778,  0.22222222)
  ( 0.88888889,  0.22222222) ( 1.        ,  0.22222222)]
 [( 0.        ,  0.33333333) ( 0.11111111,  0.33333333)
  ( 0.22222222,  0.33333333) ( 0.33333333,  0.33333333)
  ( 0.44444444,  0.33333333) ( 0.55555556,  0

**39. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))**

In [32]:
X, Y = np.random.random(10), np.random.random(10)
C = 1 / (X - Y)

**40. Print the minimum and maximum representable value for each numpy scalar type**

In [58]:
print(*[np.iinfo(dtype).min for dtype in [np.int8, np.int16, np.int32, np.int64]])
print(*[np.iinfo(dtype).max for dtype in [np.int8, np.int16, np.int32, np.int64]])
print(*[np.finfo(dtype).min for dtype in [np.float16, np.float32, np.float64]])
print(*[np.finfo(dtype).max for dtype in [np.float16, np.float32, np.float64]])

-128 -32768 -2147483648 -9223372036854775808
127 32767 2147483647 9223372036854775807
-65504.0 -3.40282e+38 -1.79769313486e+308
65504.0 3.40282e+38 1.79769313486e+308


**41. How to print all the values of an array?**

In [66]:
arr = np.random.random(10)
print(*arr)

0.273266006912 0.462771107226 0.509146634181 0.321694942817 0.0678421264287 0.724215737998 0.241584384346 0.496900023016 0.618684677292 0.801441717999


**42. How to find the closest value (to a given scalar) in an array?**

In [68]:
arr = np.random.random(10) * 10
target = 7
print(arr)
print(arr[np.abs(arr - target).argmin()])

[ 2.27072291  1.61518726  5.52786333  3.41135491  3.93818791  2.75093107
  9.0748493   9.96534136  8.75542636  8.44950667]
8.44950666966


**43. Create a structured array representing a position (x,y) and a color (r,g,b)**

In [69]:
arr = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(arr)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]
